-- 迁移 0009：按次计价（异步任务 / 图像视频等生成类能力）
--
-- 背景：
--   对话类请求按 token 计费，而"生成一张图""生成一段视频"这类调用
--   是一次性消耗，与 token 数无关（上游本身也是按次或按张收费）。
--   若强行按 token 计费，站长要么无法为这类能力定价，要么得编造一个
--   虚假的 token 数，账目会彻底失真。
--
-- 设计说明：
--   per_call_price 表示「每调用一次扣减的站点额度」，0 表示不计费（免费）。
--   它与 prompt_price / completion_price 并存于同一张表：
--     - 对话类只看 token 价格；
--     - 生成类只看 per_call_price；
--     - 一个模型同时有两种价格也合法（例如同一模型既支持对话又支持图像生成）。
--   这样不需要第二张价格表，模型匹配逻辑（精确 → 前缀 → 通配）也能完全复用。
--
-- 兼容性：
--   ALTER TABLE ADD COLUMN 带默认值 0，对历史数据即"按次免费"，
--   行为与本次升级前一致（不产生任何新增扣费），不会造成账目突变。

ALTER TABLE model_prices ADD COLUMN per_call_price INTEGER NOT NULL DEFAULT 0;
